[package]
name = "hello-rust"
version = "0.1.0"
authors = ["dragan1810 <d.novakovic1810@yahoo.com>"]
edition = "2018"

# scripts

# start: systemfd --no-pid -s http::3000 -- cargo watch -x run

[dependencies]
actix-web = "1.0.0-beta.3"
env_logger = "0.6.1"
futures = "0.1.26"
actix-files = "0.1.0-beta.1"
actix-session = "0.1.0-beta.2"
bytes = "0.4"
actix-rt = "0.2"
listenfd = "0.3"
serde = "1.0.91"
serde_derive = "^1.0.91"
serde_json = "1.0.39"
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "uuid"] }
dotenv = "0.14.0"
dotenv_codegen = "0.14.0"
uuid = { version = "0.6.5", features = ["serde", "v4"] }